cepdnaclk/e20-co225-Erasmus-plus-Project-Web-and-MIS

- back-end/src/main/java/com/example/demo/registration/RegistrationService.java
- front-end/src/Pages/Contact.jsx
- front-end/src/Pages/Gallery.jsx
- front-end/src/Pages/Login.jsx
- front-end/src/components/Header.css
- front-end/src/components/Header.jsx
visibility changed depending on whether a user is logged or not
> admin navbar visibility

- back-end/src/main/java/com/example/demo/appuser/AppUser.java
- back-end/src/main/java/com/example/demo/news/NewsAndEvents.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsController.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsRepository.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsRequest.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsService.java
- back-end/src/main/java/com/example/demo/registration/RegistrationController.java
- back-end/src/main/java/com/example/demo/registration/RegistrationService.java
- back-end/src/main/java/com/example/demo/security/config/WebSecurityConfig.java
- front-end/src/App.jsx
- front-end/src/Pages/News.jsx
- front-end/src/components/News.css
> News And Events Page Updated

- back-end/src/test/java/com/example/demo/NewsAndEventsControllerTest.java
- back-end/src/test/java/com/example/demo/NewsAndEventsServiceTest.java
Junit tests for news and event backend, controller and server classes
> Junit tests

- back-end/src/test/java/com/example/demo/DemoApplicationTests.java
- back-end/src/test/java/com/example/demo/NewsAndEventsControllerTest.java
- back-end/src/test/java/com/example/demo/NewsAndEventsServiceTest.java
Description for each test conducted, to show the purpose of the tests
> Comments for unit tests

- front-end/src/components/Header.css
- front-end/src/components/Header.jsx
> Updated Header

- front-end/src/Pages/Downloads.jsx
Only logged in users can Upload and delete files
> Updated the downloads page

- .idea/workspace.xml
- .vscode/settings.json
- back-end/src/main/java/com/example/demo/appuser/AppUser.java
- back-end/src/main/java/com/example/demo/appuser/AppUserController.java
- back-end/src/main/java/com/example/demo/appuser/AppUserRepository.java
- back-end/src/main/java/com/example/demo/appuser/AppUserService.java
- back-end/src/main/java/com/example/demo/registration/LoginResponse.java
- back-end/src/main/java/com/example/demo/registration/RegistrationService.java
- back-end/src/main/java/com/example/demo/security/config/WebSecurityConfig.java
- back-end/src/main/java/com/example/demo/task/Task.java
- back-end/src/main/java/com/example/demo/task/TaskController.java
- back-end/src/main/java/com/example/demo/task/TaskRepository.java
- back-end/src/main/java/com/example/demo/task/TaskService.java
- back-end/src/main/resources/application.yml
- front-end/package-lock.json
- front-end/package.json
- front-end/src/Pages/Login.jsx
- front-end/src/Pages/Login.module.css
- front-end/src/Pages/News.jsx
- front-end/src/Pages/ProjectManagement.jsx
- front-end/src/components/Header.jsx
- front-end/src/components/ProjectManagement.module.css
- front-end/src/main.jsx
tasks view according to user role
> tasks added

- back-end/src/main/resources/application.yml
- front-end/src/Pages/Downloads.jsx
- front-end/src/components/Team.css
Updated the downloads page where it again ask to confirm deleting when deleting a file.
> Updates on Downloads page

- front-end/src/components/News.css
> Updated news page

- front-end/src/Pages/Downloads.jsx
- front-end/src/components/Download.css
Updated the frontend of the downloads page
> updated downloads page

- back-end/src/main/java/com/example/demo/appuser/AppUser.java
- back-end/src/main/java/com/example/demo/download/FileRepository.java
- front-end/src/Pages/News.jsx
- front-end/src/components/News.css
News Form at front-end Updated
> Add news button on front-end Updated

- back-end/src/main/java/com/example/demo/appuser/AppUser.java
- back-end/src/main/java/com/example/demo/task/Task.java
- back-end/src/main/java/com/example/demo/task/TaskController.java
- front-end/src/Pages/ProjectManagement.jsx
- front-end/src/components/ProjectManagement.module.css
task delete for front end and back end
> task delete

- front-end/src/Pages/Home.jsx
- front-end/src/Pages/Home.module.css
added some css style to the home page
> home page updated

- back-end/src/main/java/com/example/demo/download/FileController.java
- back-end/src/main/java/com/example/demo/download/FileEntity.java
- back-end/src/test/java/com/example/demo/FileControllerTest.java
- front-end/package-lock.json
- front-end/package.json
- front-end/src/Pages/Downloads.jsx
- front-end/src/components/Download.css
- front-end/src/components/Header.css
Added extra features to the downloads page
> Downloads page Updated

- back-end/src/main/java/com/example/demo/news/NewsAndEvents.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsController.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsRequest.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsResponse.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsService.java
- back-end/src/test/java/com/example/demo/NewsAndEventsControllerTest.java
- back-end/src/test/java/com/example/demo/NewsAndEventsServiceTest.java
- front-end/package-lock.json
- front-end/package.json
- front-end/src/Pages/News.jsx
Images can be stored in the database
> Adding cover images to News and Events

- back-end/src/main/java/com/example/demo/gallery/Gallery.java
- back-end/src/main/java/com/example/demo/gallery/GalleryController.java
- back-end/src/main/java/com/example/demo/gallery/GalleryRepository.java
- back-end/src/main/java/com/example/demo/gallery/GalleryRequest.java
- back-end/src/main/java/com/example/demo/gallery/GalleryResponse.java
- back-end/src/main/java/com/example/demo/gallery/GalleryService.java
- back-end/src/main/java/com/example/demo/news/NewsAndEvents.java
- back-end/src/main/java/com/example/demo/news/NewsAndEventsController.java
- back-end/src/main/resources/application.yml
- front-end/src/Pages/Gallery.jsx
- front-end/src/Pages/Login.jsx
- front-end/src/Pages/News.jsx
- front-end/src/components/Gallery.css
Cover images can be selected and stored in the database
> Albums adding button added

- front-end/src/Pages/Team.jsx
- front-end/src/components/Team.css
The team page updated with tabs specific to the universities
> Team page Updated

- front-end/src/Pages/Contact.jsx
- front-end/src/components/Contact.css
> Contact page updated

- back-end/src/test/java/com/example/demo/FileControllerTest.java
- back-end/src/test/java/com/example/demo/FileServiceTest.java
> JUnit Tests for FileController and FileService

- back-end/src/test/java/com/example/demo/GalleryControllerTest.java
- back-end/src/test/java/com/example/demo/GalleryServiceTest.java
- back-end/src/test/java/com/example/demo/NewsAndEventsControllerTest.java
- back-end/src/test/java/com/example/demo/NewsAndEventsServiceTest.java
- back-end/src/test/java/com/example/demo/WorkplanServiceTest.java
Testing done on the relevant files
> JUnit tests on Gallery, News & Events, and Workplan

- back-end/src/main/java/com/example/demo/task/TaskService.java
- back-end/src/test/java/com/example/demo/DeliverableServiceTest.java
- back-end/src/test/java/com/example/demo/FileControllerTest.java
- back-end/src/test/java/com/example/demo/FileServiceTest.java
- back-end/src/test/java/com/example/demo/GalleryControllerTest.java
- back-end/src/test/java/com/example/demo/GalleryServiceTest.java
- back-end/src/test/java/com/example/demo/NewsAndEventsControllerTest.java
- back-end/src/test/java/com/example/demo/NewsAndEventsServiceTest.java
- back-end/src/test/java/com/example/demo/WorkplanServiceTest.java
Some more Unit test updates on Downloads, Gallery, News and Events, and Workplan pages.
> JUnit Tests on DeliverableService file

- front-end/src/Pages/Gallery.jsx
- front-end/src/Pages/News.jsx
- front-end/src/components/News.css
Reverts cepdnaclk/e20-co225-Erasmus-plus-Project-Web-and-MIS#108
> Revert "Update on News"

- front-end/src/Pages/News.jsx
Reverts cepdnaclk/e20-co225-Erasmus-plus-Project-Web-and-MIS#109
> Revert "Update News.jsx"

- back-end/src/main/java/com/example/demo/projectSummary/Project.java
- back-end/src/main/java/com/example/demo/projectSummary/ProjectController.java
- back-end/src/main/java/com/example/demo/projectSummary/ProjectRepository.java
- back-end/src/main/java/com/example/demo/projectSummary/ProjectService.java
- back-end/src/main/java/com/example/demo/projectSummary/ResourceNotFoundException.java
- back-end/src/main/java/com/example/demo/security/config/WebSecurityConfig.java
- front-end/src/Pages/Home.jsx
- front-end/src/components/Home.module.css
Updated the project Summary in the Home page
> Editable Project Summary

- front-end/src/Pages/Repository.jsx
- front-end/src/components/Repository.module.css
Repository page tab underline feature updated
> Repository page Updated

- front-end/src/Pages/Contact.jsx
Updated the contact form so that anyone can send emails through it.
> Updated the contact page

- front-end/src/components/Footer.jsx
Removed Login from main navigation
> Updated the footer

- front-end/src/Pages/Dashboard.jsx
- front-end/src/components/Dashboard.module.css
Added a table to display tasks in the dashboard
> Updated the Dashboard

- back-end/src/main/java/com/example/demo/notification/NotificationService.java
- front-end/package-lock.json
- front-end/package.json
- front-end/src/Pages/ProjectManagement.jsx
Email sending with notification only when assigning tasks
> Email sending with notification updated

- back-end/src/main/java/com/example/demo/task/Task.java
- back-end/src/main/java/com/example/demo/task/TaskRepository.java
- back-end/src/main/java/com/example/demo/task/TaskService.java
- front-end/src/Pages/ProjectManagement.jsx
- front-end/src/components/Header.jsx
financial plan can be updated. notifications on user login
> task and header

- front-end/src/Pages/ProjectManagement.jsx
Loading sign for adding a task
> Project Management page Updated
